# Generated by Django 6.1.1 on 2026-09-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activo", models.BooleanField(default=True)),
                (
                    "turno",
                    models.CharField(
                        choices=[("M", "Mañana"), ("T", "Tarde"), ("N", "Noche")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
