# Generated by Django 6.1.1 on 2026-09-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
