# Generated by Django 6.1.1 on 2026-09-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0002_alumno_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="apellido",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
