# Generated by Django 6.1.1 on 2026-09-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0003_alter_alumno_apellido"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="clave",
            field=models.IntegerField(default=0),
        ),
    ]
