# Generated by Django 6.1.1 on 2026-09-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0004_alumno_clave"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="genero",
            field=models.CharField(blank=True, null=True),
        ),
    ]
