# Generated by Django 6.1.1 on 2026-09-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0005_alumno_genero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=20)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
