# Generated by Django 6.1.1 on 2026-09-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0006_mensaje"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("O", "Otro"),
                    ("N", "Prefiere de decir"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
