# Generated by Django 6.1.1 on 2026-09-18 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0007_alter_alumno_genero"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensaje",
            name="alumno",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="alumnos.alumno",
            ),
            preserve_default=False,
        ),
    ]
