# Generated by Django 6.1.1 on 2026-09-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0008_mensaje_alumno"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mensaje",
        ),
    ]
